// @generated
// This file is auto-generated by scripts/generate-registry.mjs
// Do not edit this file manually.

import type { VartaExtension } from "./types";
import PrystanokModuleExt from "./prystanok";
import VartaModuleExt from "./varta";

export const EXTENSIONS: VartaExtension[] = [
  PrystanokModuleExt,
  VartaModuleExt,
];

export function getExtensions() {
  return EXTENSIONS;
}
